[package]
name = "anki-assistant"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11.0", features = ["blocking", "json"] }
serde_json = "1.0.64"
tokio = { version = "1.11.0", features = ["full"] }
log = "0.4"
env_logger = "0.10"